### ISSUE TITLE
Where is 0.3.5?

### ISSUE THREAD

**Issue by NanaLich** [Fody/Immutable#3]

**Comment by SimonCropp** [comment]
is there something that is meant to be fixed in .3.5?

**Comment by SimonCropp** [comment]
ok dont know what to do here. add more context and we can re open

**Comment by NanaLich** [comment]
Oh, I failed to mention there is no 0.3.5 on NuGet

**Comment by SimonCropp** [comment]
ok understood. this has been stable for ages. i will bump to 1.0 and deploy

**Comment by SimonCropp** [comment]
pushed 1.0
